version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_PATH=/data/expense_tracker.db
    volumes:
      - ./data:/data
      - ./storage:/app/storage
    restart: unless-stopped

  # Development services
  frontend-dev:
    image: node:18
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - app

  backend-dev:
    image: golang:1.21
    command: sh -c "go mod download && go run cmd/api/main.go"
    working_dir: /app
    ports:
      - '8081:8080'
    volumes:
      - ./backend:/app
      - ./data:/data
      - ./storage:/app/storage
    environment:
      - DB_PATH=/data/expense_tracker.db
      - ENV=development
    depends_on:
      - app
